version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.${CONTAINER_NAME}.entrypoints=http"
       - "traefik.http.routers.${CONTAINER_NAME}.rule=Host(`${DOMAIN}`)"
       - "traefik.http.routers.${CONTAINER_NAME}.middlewares=https-redirect@file"
       - "traefik.http.routers.${CONTAINER_NAME}-secure.entrypoints=https"
       - "traefik.http.routers.${CONTAINER_NAME}-secure.rule=Host(`${DOMAIN}`)"
       - "traefik.http.routers.${CONTAINER_NAME}-secure.tls=true"
       - "traefik.http.routers.${CONTAINER_NAME}-secure.tls.certresolver=http"
       - "traefik.http.routers.portainer-secure.service=${CONTAINER_NAME}"
       - "traefik.docker.network=proxy"       
   redis:
     image: "redis:alpine"

volumes:
    db_data:
